services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-rafael-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    volumes:
      - ./uploads:/app/uploads
      - ./temp-orc:/app/temp-orc
    restart: unless-stopped
